const constants = {
    FETCH_USER: 'FETCH_USER',
    FETCH_USER_REPOSITORIES: 'FETCH_USER_REPOSITORIES',
    FETCH_USER_FOLLOWERS: 'FETCH_USER_FOLLOWERS',
    FETCH_USER_ORGS: 'FETCH_USER_ORGS',
    FETCH_USER_FAILED: 'FETCH_USER_FAILED',

    FETCHED_USER: 'FETCHED_USER',
    FETCHED_USER_REPOSITORIES: 'FETCHED_USER_REPOSITORIES',
    FETCHED_USER_FOLLOWERS: 'FETCHED_USER_FOLLOWERS',
    FETCHED_USER_ORGS: 'FETCHED_USER_ORGS',

    FETCH_USER_REPOSITORIES_BY_CRITERIA: 'FETCH_USER_REPOSITORIES_BY_CRITERIA',
    FETCH_USER_REPOSITORIES_BY_CRITERIA_FAILED: 'FETCH_USER_REPOSITORIES_BY_CRITERIA_FAILED',
    FETCHED_USER_REPOSITORIES_BY_CRITERIA: 'FETCHED_USER_REPOSITORIES_BY_CRITERIA',
    FETCHED_USER_REPOSITORIES_BY_CRITERIA_BEST: 'FETCHED_USER_REPOSITORIES_BY_CRITERIA_BEST',
    FETCHED_USER_REPOSITORIES_BY_CRITERIA_BEST_FAST_GROWING: 'FETCHED_USER_REPOSITORIES_BY_CRITERIA_BEST_FAST_GROWING'
}
export default constants
